import { Inter } from "next/font/google";
// import { provider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <provider>{children}</provider> */}
        {children}
      </body>
    </html>
  );
}
